# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyAppProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Aspects', '~> 1.4.1'

  # Pods for MyAppProject

  target 'MyAppProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAppProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
